baseURL = "https://musync.link/"
languageCode = "en-ie"
title = "Synchronizing playlists across music services"
theme = "ace-documentation"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
ordersectionsby = "weight"
disableSearch = true
highlightClientSide = false
menushortcutsnewtab = false
toc = true
  [params.donate]
  side = "left"
  paypal = "ZT649R3GUBARS"
  bitcoin = "3Pnkw8BUeAwo4x2U4h7qbxLTCPDgjLLxwD"
  [params.aads]
    id = 1516558
    [params.aads.notice]
    msg = "Ethical ads help to keep this site running"
    link = "privacy-policy"
    [params.aads.top]
    width = 320
    height = 50
    [params.aads.right]
    width = 120
    height = 600

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4

[[menu.shortcuts]]
name = "by Chuso.net"
url = "https://chuso.net"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/chusopr/musync"
weight = 2

[[menu.shortcuts]]
name = "<button class='btn btn-success mt-n1'>Download</button>"
url = "https://github.com/chusopr/musync/releases"
weight = 3
